server:
  port: 8081

vapeit:
  api-url: http://localhost:8080/api/items
  report-url: http://localhost:8080/api/orders/status

reorder:
  cron: "0 * * * * *"

eciglogistica:
  url: https://nueva.eciglogistica.com
  username:
  password:

vaperalia:
  url: https://vaperalia.com
  username:
  password:

playwright:
  headless: true
