server:
  port: 8081

vapeit:
  api-url: http://localhost:8080/api/items
  report-url: http://localhost:8080/api/orders/status

reorder:
  cron: "0 * * * * *"

eciglogistica:
  url: https://nueva.eciglogistica.com
  username: ${ECIGLOGISTICA_USERNAME:}
  password: ${ECIGLOGISTICA_PASSWORD:}

vaperalia:
  url: https://vaperalia.es
  username: ${VAPERALIA_USERNAME:}
  password: ${VAPERALIA_PASSWORD:}
  session-file: vaperalia-session.json

playwright:
  headless: true
